### ISSUE TITLE
new instalation don't works

### ISSUE THREAD

**Issue by riguelbf** [lopidio/stacker#21]
npm install can't make download of all dependencies. I tried to perform even forcing with new versions of packages. Please review the dependencies.

**Comment by lopidio** [comment]
This is weird.
It has to be installed with no optional dependencies.
Are you sure you tried running?

```rm -rf node_modules package-lock.json && npm i --no-optional```

Let me know how it goes.

**Comment by riguelbf** [comment]
ready, it's working again

**Comment by lopidio** [comment]
Nice.
